!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        01oY3L0F-Collateral Types:
          path: dataset/01oY3L0F-Collateral Types
          prefix: ncino
          standardFeature: true
          versions:
            Fall 2019 V3:
              modifiedDate: '2022-04-11 14:25:07'
        01oY3L0F-Document Manager:
          path: dataset/01oY3L0F-Document Manager
          prefix: ncino
          standardFeature: false
          versions:
            Spring 2020 V1:
              modifiedDate: '2022-04-12 18:29:30'
        01oY3L0F-Id Doc Type Test:
          path: dataset/01oY3L0F-Id Doc Type Test
          prefix: ncino
          standardFeature: false
          versions:
            24 May 21:
              modifiedDate: '2022-04-11 13:21:26'
